// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdhif3QV2_2gxz2-bhbjyoSjtPyxrRab4',
    appId: '1:167727942483:web:ba34950d600d0525716fa6',
    messagingSenderId: '167727942483',
    projectId: 'gdsc-flutterstudy-udemy-chat',
    authDomain: 'gdsc-flutterstudy-udemy-chat.firebaseapp.com',
    storageBucket: 'gdsc-flutterstudy-udemy-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-B2PKaYrj4wGL1cloFFzfGcXONn1Y9Nc',
    appId: '1:167727942483:android:e119d8eaa1b4c672716fa6',
    messagingSenderId: '167727942483',
    projectId: 'gdsc-flutterstudy-udemy-chat',
    storageBucket: 'gdsc-flutterstudy-udemy-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsh7Q-Ebdl-yxto-wYvFnFLVJ9_nj5TQA',
    appId: '1:167727942483:ios:498393434aecd07c716fa6',
    messagingSenderId: '167727942483',
    projectId: 'gdsc-flutterstudy-udemy-chat',
    storageBucket: 'gdsc-flutterstudy-udemy-chat.appspot.com',
    iosBundleId: 'com.example.wwwave_frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsh7Q-Ebdl-yxto-wYvFnFLVJ9_nj5TQA',
    appId: '1:167727942483:ios:8146ce82ba2a9f47716fa6',
    messagingSenderId: '167727942483',
    projectId: 'gdsc-flutterstudy-udemy-chat',
    storageBucket: 'gdsc-flutterstudy-udemy-chat.appspot.com',
    iosBundleId: 'com.example.wwwave_frontend.RunnerTests',
  );
}
